### ISSUE TITLE
Weird StackOverflowError

### ISSUE THREAD

**Issue by Radviger** [tomlj/tomlj#31]
Following lines cause stack overflow with no adequate call site information:

```toml
[group.child]
b="B"

[group]
a="A"
```

Yet if I declare [group] prior to [group.child] - everything works fine.
